api_platform:
    title: PruebaTecnicaProyectos API
    version: 1.0.0
    defaults:
        stateless: true
        formats:
            jsonld: ['application/ld+json']
            json: ['application/json']
        patch_formats:
            json: ['application/json']
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
